blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/coreyshort/arche/discussions
    about: For general questions and discussions about the template system
  - name: Documentation
    url: https://github.com/coreyshort/arche#readme
    about: Read the full documentation
